"""add chat configs

Revision ID: 18d943de40ed
Revises: a54586e1e775
Create Date: 2026-07-04 08:37:41.649388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d943de40ed'
down_revision = 'a54586e1e775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canned_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortcut', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcut')
    )
    op.create_table('chat_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_setting')
    op.drop_table('canned_response')
    # ### end Alembic commands ###
